--CREATE DATABASE ECOMMERCE2;

-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PRODUTO_ESTOQUE (
ID_ESTOQUE INTEGER PRIMARY KEY,
ID_PRODUTO INTEGER
);

CREATE TABLE PESSOA_TIPO (
ID_PESSOA_TIPO INTEGER PRIMARY KEY,
NOME_TIPO VARCHAR(100)
);

CREATE TABLE USUARIO (
ID_USUARIO INTEGER PRIMARY KEY,
LOGIN VARCHAR(20),
SENHA VARCHAR(30),
ATIVO BOOLEAN,
ID_PESSOA INTEGER
);

CREATE TABLE PEDIDO (
ID_PEDIDO INTEGER PRIMARY KEY,
DATA_PAGAMENTO DATE,
DATA_PEDIDO DATE,
ID_USUARIO INTEGER,
ID_FRETE INTEGER,
FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PRODUTO (
ID_PRODUTO INTEGER PRIMARY KEY,
DESCRICAO VARCHAR(255),
VALOR DOUBLE PRECISION,
ID_PESSOA INTEGER,
id_categoria INTEGER
);

CREATE TABLE CATEGORIA (
id_categoria INTEGER PRIMARY KEY,
cat_descricao VARCHAR(255)
);

CREATE TABLE IMAGENS (
id_imagem INTEGER PRIMARY KEY,
img_descricao VARCHAR(255),
ID_PRODUTO INTEGER,
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE ENDERECO (
ID_PESSOA INTEGER PRIMARY KEY,
CEP VARCHAR(8),
PAIS VARCHAR(100),
NUMERO INTEGER,
CIDADE VARCHAR(100),
RUA VARCHAR(150)
);

CREATE TABLE PESSOA (
ID_PESSOA INTEGER PRIMARY KEY,
NOME VARCHAR(100),
DATA_NASC DATE,
CPF_CNPJ VARCHAR(14),
FILIAL BOOLEAN,
ID_PESSOA_TIPO INTEGER,
ID_ESTOQUE INTEGER,
FOREIGN KEY(ID_PESSOA_TIPO) REFERENCES PESSOA_TIPO (ID_PESSOA_TIPO),
FOREIGN KEY(ID_ESTOQUE) REFERENCES PRODUTO_ESTOQUE (ID_ESTOQUE)
);

CREATE TABLE ITEM_PEDIDO (
ID_ESTOQUE INTEGER,
ID_PEDIDO INTEGER,
PRIMARY KEY(ID_ESTOQUE,ID_PEDIDO),
FOREIGN KEY(ID_ESTOQUE) REFERENCES PRODUTO_ESTOQUE (ID_ESTOQUE),
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE FRETE (
ID_FRETE INTEGER PRIMARY KEY,
FAIXA_DE VARCHAR(8),
FAIXA_ATE VARCHAR(8),
VALOR_FRETE DOUBLE PRECISION,
ID_TRANSPORTE INTEGER
);

CREATE TABLE TRANSPORTE (
ID_TRANSPORTE INTEGER PRIMARY KEY,
NOME_TRANSPORTE VARCHAR(100),
ATIVO BOOLEAN
);

ALTER TABLE PRODUTO_ESTOQUE ADD FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO);
ALTER TABLE USUARIO ADD FOREIGN KEY(ID_PESSOA) REFERENCES pessoa (ID_PESSOA);
ALTER TABLE PEDIDO ADD FOREIGN KEY(ID_FRETE) REFERENCES FRETE (ID_FRETE);
ALTER TABLE PRODUTO ADD FOREIGN KEY(ID_PESSOA) REFERENCES pessoa (ID_PESSOA);
ALTER TABLE PRODUTO ADD FOREIGN KEY(id_categoria) REFERENCES Categoria (id_categoria);
ALTER TABLE Endereco ADD FOREIGN KEY(ID_PESSOA) REFERENCES pessoa (ID_PESSOA);
ALTER TABLE FRETE ADD FOREIGN KEY(ID_TRANSPORTE) REFERENCES TRANSPORTE (ID_TRANSPORTE);
